easy-base:
    initialization:
        admin-user:
            display-name: Administrator
            email: admin@easybase.com
            first-name: Admin
            last-name: User
            password: admin123
        enabled: true
    docmediastore:
        root:
            folder: file_system
        file:
            included: png,jpeg,jpg
            size: 500000000
logging:
    level:
        com.easybase: DEBUG
        org.hibernate: INFO
        org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
        org.springframework.web: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
server:
    port: 8080
    servlet:
        context-path: /
spring:
    application:
        name: easy-base
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://localhost:5432/easybase
        username: postgres
    jackson:
        deserialization:
            fail-on-unknown-properties: false
        modules:
            - com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
        serialization:
            write-dates-as-timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    profiles:
        active: development
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB